"""Add_column_datetime_all_table_1

Revision ID: 3c1337a45d4b
Revises: f05c1f1e2048
Create Date: 2025-03-18 09:20:29.819829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1337a45d4b'
down_revision: Union[str, None] = 'f05c1f1e2048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Inventory', sa.Column('CreatedDate', sa.DateTime(), nullable=True))
    op.add_column('MaintenanceRequestDetails', sa.Column('CreatedDate', sa.DateTime(), nullable=True))
    op.add_column('MaintenanceRequestDetails', sa.Column('LastUpdated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MaintenanceRequestDetails', 'LastUpdated')
    op.drop_column('MaintenanceRequestDetails', 'CreatedDate')
    op.drop_column('Inventory', 'CreatedDate')
    # ### end Alembic commands ###
