"""Initial migration

Revision ID: 43cff1c3c7d4
Revises: 
Create Date: 2025-03-17 07:57:06.427654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43cff1c3c7d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MaintenanceRequests',
    sa.Column('RequestID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RequestNumber', sa.String(length=50), nullable=False),
    sa.Column('MachineName', sa.String(length=255), nullable=True),
    sa.Column('Diagnosis', sa.String(length=500), nullable=True),
    sa.Column('RequestedBy', sa.String(length=100), nullable=True),
    sa.Column('RequestDate', sa.DateTime(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('RequestID'),
    sa.UniqueConstraint('RequestNumber')
    )
    op.create_index(op.f('ix_MaintenanceRequests_RequestID'), 'MaintenanceRequests', ['RequestID'], unique=False)
    op.create_table('Materials',
    sa.Column('MaterialID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaterialCode', sa.String(length=50), nullable=False),
    sa.Column('MaterialName', sa.String(length=255), nullable=False),
    sa.Column('ImageUrl', sa.String(length=500), nullable=True),
    sa.Column('Model', sa.String(length=100), nullable=True),
    sa.Column('Origin', sa.String(length=100), nullable=True),
    sa.Column('Unit', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('MaterialID'),
    sa.UniqueConstraint('MaterialCode')
    )
    op.create_index(op.f('ix_Materials_MaterialID'), 'Materials', ['MaterialID'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.create_table('Warehouses',
    sa.Column('WarehouseID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('WarehouseName', sa.String(length=255), nullable=False),
    sa.Column('Location', sa.String(length=255), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('WarehouseID')
    )
    op.create_index(op.f('ix_Warehouses_WarehouseID'), 'Warehouses', ['WarehouseID'], unique=False)
    op.create_table('Inventory',
    sa.Column('InventoryID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('WarehouseID', sa.Integer(), nullable=False),
    sa.Column('MaterialID', sa.Integer(), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('LastUpdated', sa.DateTime(), nullable=False),
    sa.CheckConstraint('Quantity > 0', name='chk_quantity_non_negative'),
    sa.ForeignKeyConstraint(['MaterialID'], ['Materials.MaterialID'], ),
    sa.ForeignKeyConstraint(['WarehouseID'], ['Warehouses.WarehouseID'], ),
    sa.PrimaryKeyConstraint('InventoryID')
    )
    op.create_index(op.f('ix_Inventory_InventoryID'), 'Inventory', ['InventoryID'], unique=False)
    op.create_table('MaintenanceRequestDetails',
    sa.Column('RequestDetailID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('RequestID', sa.Integer(), nullable=False),
    sa.Column('MaterialID', sa.Integer(), nullable=False),
    sa.Column('WarehouseID', sa.Integer(), nullable=False),
    sa.Column('QuantityUsed', sa.Integer(), nullable=False),
    sa.CheckConstraint('QuantityUsed > 0', name='check_quantity_used_positive'),
    sa.ForeignKeyConstraint(['MaterialID'], ['Materials.MaterialID'], ),
    sa.ForeignKeyConstraint(['RequestID'], ['MaintenanceRequests.RequestID'], ),
    sa.ForeignKeyConstraint(['WarehouseID'], ['Warehouses.WarehouseID'], ),
    sa.PrimaryKeyConstraint('RequestDetailID')
    )
    op.create_index(op.f('ix_MaintenanceRequestDetails_RequestDetailID'), 'MaintenanceRequestDetails', ['RequestDetailID'], unique=False)
    op.create_table('StockHistory',
    sa.Column('StockHistoryID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('WarehouseID', sa.Integer(), nullable=False),
    sa.Column('MaterialID', sa.Integer(), nullable=False),
    sa.Column('QuantityChange', sa.Integer(), nullable=False),
    sa.Column('ChangeType', sa.String(length=50), nullable=False),
    sa.Column('ReferenceID', sa.Integer(), nullable=False),
    sa.Column('ReferenceType', sa.String(length=50), nullable=False),
    sa.Column('ChangeDate', sa.DateTime(), nullable=False),
    sa.CheckConstraint("ChangeType IN ('Export','Import')", name='check_change_type'),
    sa.CheckConstraint("ReferenceType IN ('MaintenanceRequest','ManualInput')", name='check_reference_type'),
    sa.ForeignKeyConstraint(['MaterialID'], ['Materials.MaterialID'], ),
    sa.ForeignKeyConstraint(['WarehouseID'], ['Warehouses.WarehouseID'], ),
    sa.PrimaryKeyConstraint('StockHistoryID')
    )
    op.create_index(op.f('ix_StockHistory_StockHistoryID'), 'StockHistory', ['StockHistoryID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_StockHistory_StockHistoryID'), table_name='StockHistory')
    op.drop_table('StockHistory')
    op.drop_index(op.f('ix_MaintenanceRequestDetails_RequestDetailID'), table_name='MaintenanceRequestDetails')
    op.drop_table('MaintenanceRequestDetails')
    op.drop_index(op.f('ix_Inventory_InventoryID'), table_name='Inventory')
    op.drop_table('Inventory')
    op.drop_index(op.f('ix_Warehouses_WarehouseID'), table_name='Warehouses')
    op.drop_table('Warehouses')
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Materials_MaterialID'), table_name='Materials')
    op.drop_table('Materials')
    op.drop_index(op.f('ix_MaintenanceRequests_RequestID'), table_name='MaintenanceRequests')
    op.drop_table('MaintenanceRequests')
    # ### end Alembic commands ###
