version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: hien_dev
      RABBITMQ_DEFAULT_PASS: Hien@2024
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  py_api:
    build:
      context: ./backend
    container_name: py_api
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./backend/app/public/images:/app/public/images
    env_file:
      - .env.prod    
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "${PORT}:${PORT}"   # map 9600:9600
    restart: always

  vue_frontend:
    build:
      context: ./frontend
    container_name: vue_frontend
    ports:
      - "5173:443"
    depends_on:
      - py_api
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/cert/localhost.crt:/etc/nginx/conf.d/localhost.crt
      - ./frontend/cert/localhost.key:/etc/nginx/conf.d/localhost.key
    restart: always
